### ISSUE TITLE
is this legal to do so?

### ISSUE THREAD

**Issue by mohammad-zadeed** [ahsanf/bigsur-abstract-dynamic-wallpaper-on-ubuntu#1]
Hi there, I came across your wallpaper on GitHub and I think it looks great! I was wondering if you have the legal rights to distribute it, as I want to make sure I'm not infringing any copyrights if I were to use it. Thank you for your time

**Comment by ahsanf** [comment]
Hi @mohammad-zadeed, thanks for the reminder. So, about the license, I don't know the details. But I'm sure if it's only used for personal use it's okay. To guarantee and avoid copyrights issues, I will issue an image file in the repo. Thank you so much !
