### ISSUE TITLE
Question about the legal use of copyrighted material

### ISSUE THREAD

**Issue by mohammad-zadeed** [ahsanf/bigsur-abstract-dynamic-wallpaper-on-ubuntu#2]
Hello again! You mentioned that it's okay to use this wallpaper for personal use & i got  your point. However, I was curious about the previous ban of Pear OS. Do you have any idea why it was banned even if personal use doesn't violate copyright law? 
Thank you for your time and input.

**Comment by ahsanf** [comment]
Hello @mohammad-zadeed, it can happen because the pear OS dont have any legal license to distribute and and can go against the provisions of other companies. All i know Pear OS is one of Ubuntu-based Linux distribution, so it should be safe. Correct me if i wrong
